name: Get Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every sunday

jobs:
  get-data:
    name: Get Data
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Get Data
        env:
          MMR_CLIENT_ID: ${{ secrets.MMR_CLIENT_ID }}
          MMR_AUTH_TOKEN: ${{ secrets.MMR_AUTH_TOKEN }}
          MMR_USER_ID: ${{ secrets.MMR_USER_ID }}
        run: pnpm get-data
